### ISSUE TITLE
Is this working with related model inserts?

### ISSUE THREAD

**Issue by lambrojos** [fullcube/loopback-ds-readonly-mixin#1]
Hi,
I suspect that this won't work if  the model is updated through a relationship, as the beforeRemote hook won't intercept updates in methods such as `Model.prototype.__update__<relation>`

I think that if that is true it should be mentioned in the documentation :)

**Comment by lambrojos** [comment]
Ok it looks like there is an easy workaround:
for example, if we have an Address model with some readonly properties and we also have a Customer model with an hasOne relation to the Address model, we can just do something like:

```
Customer.beforeRemote('prototype.__update__address',  Address.stripReadOnlyProperties)


```

**Comment by casamia918** [comment]
Hi. Can you share the full Custmor.js code? How did you get the 'Address' instance?

**Comment by mrfelton** [comment]
@casamia918 the latest release should now properly support relationships. This was implemented in this PR https://github.com/fullcube/loopback-ds-readonly-mixin/pull/13/files

**Comment by casamia918** [comment]
@mrfelton Thanks. I solved.

In the MyUser.js script, I added this beforeRemote hook. MyUser has many Contact. Contact has read-only property named 'name'.

```
module.exports = function(MyUser) {

  MyUser.beforeRemote('prototype.__updateById__contacts', function(ctx, instance, next) {
    const Contact = MyUser.app.models.Contact;
    Contact.stripReadOnlyProperties('Contact', ctx,next);
  });
};

```

For those who find whole code, I attached my sample project. 
Before start, run `npm install` to install node modules.

[reproducing-app.zip](https://github.com/fullcube/loopback-ds-readonly-mixin/files/1007668/reproducing-app.zip)

**Comment by mrfelton** [comment]
Again, you shouldn't need to do that @casamia918 as the mixin handles it for you. All you need to do is define the relationships. You will also need to define the inverse relationship to though, from  `Contact` back to `MyUser`

**Comment by casamia918** [comment]
@mrfelton Hm... When I just define the relationship, readonly is not working. (Ofcourse, I define the inverse relationship - Contact belongsTo MyUser) Can you check my sample project? When I comment out the before remote hook, the related model's readonly property can be updated by __updateById__contacts method. (The rest api endpoint is PUT /MyUsers/{id}/contacts/{fk} ) I tested this in the api explorer.

I'm using loopback 3.

**Comment by casamia918** [comment]
Did I do something wrong? I'm glad to hear your reply..

**Comment by mrfelton** [comment]
@casamia918 so I think you have uncovered a bug with the implementation. It currently only works if the parent model also has the ReadOnly mixin enabled.

Try with the following patch to your repo.

To work around the issue I have applied the mixin to the myUser model and enabled it on some non-existant properly. It'll have no effect on the actual myUser model, but it will cause the mixin to look at the relationships of that model and take the appropriate action

```patch
commit a3143728eb7a52c77567e396606256deb209262d
Author: Tom Kirkpatrick <tom@systemseed.com>
Date:   Wed May 17 16:01:30 2017 +0200

    adjustments

diff --git a/common/models/my-user.js b/common/models/my-user.js
index 4df35e5..4b28c07 100644
--- a/common/models/my-user.js
+++ b/common/models/my-user.js
@@ -1,9 +1,4 @@
 'use strict';

 module.exports = function(MyUser) {
-
-  MyUser.beforeRemote('prototype.__updateById__contacts', function(ctx, instance, next) {
-    const Contact = MyUser.app.models.Contact;
-    Contact.stripReadOnlyProperties('Contact', ctx,next);
-  });
 };
diff --git a/common/models/my-user.json b/common/models/my-user.json
index 7ef244a..56c7925 100644
--- a/common/models/my-user.json
+++ b/common/models/my-user.json
@@ -5,6 +5,11 @@
   "options": {
     "validateUpsert": true
   },
+  "mixins": {
+    "ReadOnly": {
+      "non-existant-property": true
+    }
+  },
   "properties": {
     "name": {
       "type": "string"
diff --git a/server/server.js b/server/server.js
index 35d8b95..ef738ab 100644
--- a/server/server.js
+++ b/server/server.js
@@ -17,7 +17,6 @@ app.start = function() {
     }
   });
 };
-require('loopback-ds-readonly-mixin')(app);

 // Bootstrap the application, configure models, datasources and middleware.
 // Sub-apps like REST API are mounted via boot scripts.
```

Also note that you don't need to manually require the mixin in server.js - that is a legacy solution and the preferred approach is to just use the mixin sources in model-config.json

**Comment by casamia918** [comment]
Wow thanks! I don't know that ReadOnly mixin should be declared in the mother-relationship model. Really, really thanks!
