### ISSUE TITLE
mixinSource docs are wrong/misleading?

### ISSUE THREAD

**Issue by doublemarked** [fullcube/loopback-ds-readonly-mixin#4]
Hey - we upgraded to `loopback-boot@2.8.2` and changed our `loopback-ds-readonly-mixin` config to avoid the deprecation warning. After doing so, the mixin stopped working. I believe your docs are wrong - the mixin source needs to reference the `lib` subdir, like this:

```
    "mixins": [
      "loopback/common/mixins",
      "../node_modules/loopback-ds-readonly-mixin/lib",
      "../common/mixins"
    ]
```

Once we changed that the mixin started loading again.

**Comment by geekguy** [comment]
@doublemarked : You are right. `lib` subdir is required.

**Comment by faustomorales** [comment]
Got me up and running! Thanks.

**Comment by ebarault** [comment]
certainly worth updating the Readme?

**Comment by mrfelton** [comment]
Have updated the docs. Thanks.
